---
title: 'STAT462 - Applied Regression'
subtitle: <h4 style="font-style:normal">Dr Helen Greatrex</h4>
author: <h4 style="font-style:normal">Penn State, Dept Statistics</h4>
date: <h4 style="font-style:normal">Jan, 2022</h4>
output: 
  html_document:
    theme: flatly  
    toc: false # adds a table of contents
    css: styles.css
    toc_depth: 3
    toc_float:
      collapsed: no
      smooth_scroll: yes
    number_sections: no
---


<style>
p.comment {
background-color: #DBDBDB;
padding: 10px;
border: 1px solid black;
margin-left: 25px;
border-radius: 5px;
font-style: italic;
}

.figure {
   margin-top: 20px;
   margin-bottom: 20px;
}

h1.title {
  font-weight: bold;
  font-family: Arial;  
}

h2.title {
  font-family: Arial;  
}

</style>


<style type="text/css">
#TOC {
  font-size: 13px;
  font-family: Arial;
}
</style>

</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\


Welcome to the STAT-462 Lab Book.  This website complements the class [Canvas](https://canvas.psu.edu/) site and will update each week.

On this website you will find:

* Lab tutorials 
* The labs themselves
* Links to datasets

<br>

## Giving Credit

The following websites were used in the construction of this course website. My gratitude to the people who invested their time and effort in developing and offering these valuable resources to the public.


* https://rmarkdown.rstudio.com/lesson-13.html
* Noli Brazil's wonderful lab website design for his course on [Quantitative Methods in Community Research](https://crd150.github.io/index.html)




***


Website created and maintained by [Helen Greatrex](https://www.geog.psu.edu/directory/helen-greatrex). Website template by [Noli Brazil](https://nbrazil.faculty.ucdavis.edu/)